In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
# load the data
df = pd.read_csv('../data/pcos_prediction_dataset.csv')
df.head()

,Country,Age,BMI,Menstrual Regularity,Hirsutism,Acne Severity,Family History of PCOS,Insulin Resistance,Lifestyle Score,Stress Levels,Urban/Rural,Socioeconomic Status,Awareness of PCOS,Fertility Concerns,Undiagnosed PCOS Likelihood,Ethnicity,Diagnosis
0,Madagascar,26,Overweight,Regular,Yes,Severe,Yes,Yes,2,Low,Rural,High,Yes,No,0.107938,Hispanic,Yes
1,Vietnam,16,Underweight,Regular,Yes,NaN,No,Yes,4,High,Rural,Middle,Yes,No,0.156729,Other,No
2,Somalia,41,Normal,Regular,No,Moderate,No,No,7,Medium,Urban,Middle,Yes,Yes,0.202901,Other,No
3,Malawi,27,Normal,Irregular,No,Mild,No,No,10,Low,Urban,High,Yes,No,0.073926,Caucasian,Yes
4,France,26,Overweight,Irregular,Yes,NaN,No,No,7,Medium,Urban,Middle,No,No,0.229266,Caucasian,No

In [9]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

In [10]:
df.head()

,country,age,bmi,menstrual_regularity,hirsutism,acne_severity,family_history_of_pcos,insulin_resistance,lifestyle_score,stress_levels,urban/rural,socioeconomic_status,awareness_of_pcos,fertility_concerns,undiagnosed_pcos_likelihood,ethnicity,diagnosis
0,Madagascar,26,Overweight,Regular,Yes,Severe,Yes,Yes,2,Low,Rural,High,Yes,No,0.107938,Hispanic,Yes
1,Vietnam,16,Underweight,Regular,Yes,NaN,No,Yes,4,High,Rural,Middle,Yes,No,0.156729,Other,No
2,Somalia,41,Normal,Regular,No,Moderate,No,No,7,Medium,Urban,Middle,Yes,Yes,0.202901,Other,No
3,Malawi,27,Normal,Irregular,No,Mild,No,No,10,Low,Urban,High,Yes,No,0.073926,Caucasian,Yes
4,France,26,Overweight,Irregular,Yes,NaN,No,No,7,Medium,Urban,Middle,No,No,0.229266,Caucasian,No

In [11]:
### Check missing values
df.isnull().sum()

country                            0
age                                0
bmi                                0
menstrual_regularity               0
hirsutism                          0
acne_severity                  60085
family_history_of_pcos             0
insulin_resistance                 0
lifestyle_score                    0
stress_levels                      0
urban/rural                        0
socioeconomic_status               0
awareness_of_pcos                  0
fertility_concerns                 0
undiagnosed_pcos_likelihood        0
ethnicity                          0
diagnosis                          0
dtype: int64

In [23]:
df.tail(20)

,country,age,bmi,menstrual_regularity,hirsutism,acne_severity,family_history_of_pcos,insulin_resistance,lifestyle_score,stress_levels,urban/rural,socioeconomic_status,awareness_of_pcos,fertility_concerns,undiagnosed_pcos_likelihood,ethnicity,diagnosis
119980,Somalia,18,Underweight,Irregular,No,Mild,Yes,Yes,4,High,Urban,Low,Yes,Yes,0.115082,Other,No
119981,Ecuador,15,Normal,Regular,Yes,NaN,No,Yes,4,High,Urban,High,Yes,No,0.082719,Asian,No
119982,Zimbabwe,21,Normal,Regular,Yes,Severe,Yes,No,1,Low,Rural,High,No,Yes,0.161627,Caucasian,No
119983,Afghanistan,30,Overweight,Irregular,Yes,Mild,No,No,9,Medium,Rural,Middle,Yes,No,0.070892,Other,No
119984,Brazil,36,Obese,Regular,Yes,Mild,No,No,5,Low,Urban,Middle,No,No,0.104384,African,No
119985,Zambia,40,Normal,Regular,Yes,NaN,Yes,No,7,Medium,Urban,High,Yes,No,0.172917,African,No
119986,Spain,37,Normal,Regular,No,Severe,No,No,7,Medium,Urban,Middle,Yes,Yes,0.249953,Caucasian,No
119987,Egypt,36,Normal,Regular,No,NaN,No,No,2,Medium,Urban,Low,No,Yes,0.085712,Hispanic,No
119988,Ivory Coast,18,Underweight,Regular,No,Mild,No,No,4,Medium,Urban,Middle,Yes,Yes,0.215998,African,No
119989,Mozambique,36,Obese,Regular,No,Mild,Yes,No,2,Medium,Urban,Middle,No,No,0.086842,Asian,No
119990,Yemen,45,Overweight,Regular,Yes,NaN,No,No,6,High,Urban,Low,No,No,0.117242,Hispanic,No
119991,Mozambique,27,Normal,Regular,Yes,NaN,No,Yes,3,Medium,Urban,Middle,No,Yes,0.100742,African,No
119992,Pakistan,22,Obese,Irregular,No,NaN,No,Yes,7,Medium,Rural,Low,Yes,No,0.071900,African,No
119993,Rwanda,17,Overweight,Regular,No,NaN,Yes,No,4,High,Urban,High,No,No,0.099718,Hispanic,No
119994,Germany,44,Normal,Regular,Yes,Mild,No,Yes,4,Medium,Urban,Low,Yes,Yes,0.087747,Caucasian,No
119995,Guinea,28,Normal,Regular,No,Moderate,Yes,No,3,Low,Urban,Middle,Yes,Yes,0.090663,African,No
119996,Mozambique,35,Overweight,Regular,No,NaN,No,No,5,Low,Rural,High,Yes,Yes,0.167482,Asian,No
119997,Cambodia,16,Normal,Regular,No,Moderate,No,No,9,Medium,Rural,Low,Yes,Yes,0.236241,African,Yes
119998,Benin,15,Obese,Regular,Yes,NaN,Yes,Yes,1,Medium,Rural,High,No,No,0.119993,Hispanic,No
119999,Brazil,17,Obese,Irregular,Yes,NaN,No,No,6,Medium,Rural,Low,Yes,No,0.223073,Asian,No

### Preprocessed Data

In [17]:
df.shape

(120000, 17)

In [ ]:
### country
df.country.nunique()

77

In [22]:
df.country.value_counts().tail(30)

country
Guatemala         1547
Turkey            1546
Somalia           1545
Bangladesh        1544
Cameroon          1543
Chad              1541
Poland            1540
Sri Lanka         1535
Niger             1534
Iraq              1532
Egypt             1530
Saudi Arabia      1529
Nigeria           1528
Zimbabwe          1528
Australia         1526
Mozambique        1523
North Korea       1523
Malaysia          1522
Syria             1517
United Kingdom    1514
Taiwan            1510
Benin             1509
Nepal             1509
Venezuela         1508
Tanzania          1501
Netherlands       1500
Algeria           1496
Uganda            1487
Zambia            1479
Cambodia          1441
Name: count, dtype: int64

In [16]:
df[df['country'] == 'Bangladesh']

,country,age,bmi,menstrual_regularity,hirsutism,acne_severity,family_history_of_pcos,insulin_resistance,lifestyle_score,stress_levels,urban/rural,socioeconomic_status,awareness_of_pcos,fertility_concerns,undiagnosed_pcos_likelihood,ethnicity,diagnosis
50,Bangladesh,37,Normal,Regular,No,NaN,No,No,3,Medium,Urban,Low,Yes,Yes,0.052753,African,No
85,Bangladesh,34,Normal,Regular,No,Mild,Yes,No,1,High,Urban,Low,Yes,No,0.184029,Caucasian,No
88,Bangladesh,23,Normal,Regular,Yes,NaN,No,No,10,Medium,Urban,Middle,Yes,No,0.166652,Other,No
253,Bangladesh,20,Normal,Irregular,Yes,NaN,No,No,6,Low,Urban,Low,Yes,Yes,0.078049,Other,No
266,Bangladesh,35,Overweight,Regular,No,Moderate,Yes,No,6,Medium,Rural,Middle,No,No,0.194960,Asian,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119623,Bangladesh,18,Normal,Regular,Yes,Moderate,No,No,4,Low,Rural,Middle,No,No,0.115560,Hispanic,No
119646,Bangladesh,44,Overweight,Regular,No,NaN,No,Yes,1,High,Urban,Low,Yes,Yes,0.196038,Caucasian,No
119675,Bangladesh,45,Normal,Irregular,Yes,NaN,Yes,Yes,6,High,Rural,Middle,No,Yes,0.178414,Hispanic,No
119691,Bangladesh,32,Normal,Regular,No,NaN,No,No,2,High,Urban,Middle,No,Yes,0.239536,Asian,No
119771,Bangladesh,17,Normal,Irregular,No,Moderate,No,Yes,5,High,Urban,Middle,Yes,No,0.110407,Other,No